### ISSUE TITLE
Small molecule workflow failing with `RESTCapableHybridTopologyFactory`

### ISSUE THREAD

**Issue by ijpulidos** [choderalab/perses#1039]
When using the new `RESTCapableHybridTopologyFactory` on the `tyk2` system we use for our benchmarks, I am getting the following error:
```python
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/perses0.10.0rc/lib/python3.9/site-packages/openmmtools/cache.py", line 449, in get_context
    context = self._lru[context_id]
  File "/home/user/miniconda3/envs/perses0.10.0rc/lib/python3.9/site-packages/openmmtools/cache.py", line 151, in __getitem__
    entry = self._data.pop(key)
KeyError: (-573611878824313254, 5256018169954360784)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/lila/data/chodera/user/perses/benchmarks_tyk2_5ns_perses0.10.0rc_RESTHtf/run_benchmarks.py", line 176, in <module>
    run_relative_perturbation(lig_a_index, lig_b_index, reverse=is_reversed)
  File "/lila/data/chodera/user/perses/benchmarks_tyk2_5ns_perses0.10.0rc_RESTHtf/run_benchmarks.py", line 92, in run_relative_perturbation
    run(new_yaml)
  File "/home/user/miniconda3/envs/perses0.10.0rc/lib/python3.9/site-packages/perses/app/setup_relative_calculation.py", line 813, in run
    setup_dict = run_setup(setup_options)
  File "/home/user/miniconda3/envs/perses0.10.0rc/lib/python3.9/site-packages/perses/app/setup_relative_calculation.py", line 702, in run_setup
    hss[phase].setup(n_states=n_states, temperature=temperature, storage_file=reporter,
  File "/home/user/miniconda3/envs/perses0.10.0rc/lib/python3.9/site-packages/perses/samplers/multistate.py", line 96, in setup
    feptasks.minimize(compound_thermodynamic_state_copy, sampler_state, max_iterations=minimisation_steps)
  File "/home/user/miniconda3/envs/perses0.10.0rc/lib/python3.9/site-packages/perses/dispersed/feptasks.py", line 687, in minimize
    context, integrator = cache.global_context_cache.get_context(thermodynamic_state)
  File "/home/user/miniconda3/envs/perses0.10.0rc/lib/python3.9/site-packages/openmmtools/cache.py", line 451, in get_context
    context = thermodynamic_state.create_context(integrator, self._platform, self._platform_properties)
  File "/home/user/miniconda3/envs/perses0.10.0rc/lib/python3.9/site-packages/openmmtools/states.py", line 1171, in create_context
    system = self.get_system(remove_thermostat=is_thermostated)
  File "/home/user/miniconda3/envs/perses0.10.0rc/lib/python3.9/site-packages/openmmtools/states.py", line 2817, in get_system
    s.apply_to_system(system)
  File "/home/user/miniconda3/envs/perses0.10.0rc/lib/python3.9/site-packages/openmmtools/alchemy.py", line 373, in apply_to_system
    super().apply_to_system(system)
  File "/home/user/miniconda3/envs/perses0.10.0rc/lib/python3.9/site-packages/openmmtools/states.py", line 3521, in apply_to_system
    raise self._GLOBAL_PARAMETER_ERROR(err_msg.format(parameter_name))
openmmtools.alchemy.AlchemicalStateError: Could not find global parameter lambda_bonds in the system.
``` 
full log output in https://gist.github.com/ijpulidos/b7096cba1dba336c5c1260e885a0711d just in case something else can be spotted there.

**Comment by zhang-ivy** [comment]
@ijpulidos and I debugged this and it looks like the error is being caused by [this line](https://github.com/choderalab/perses/blob/main/perses/app/setup_relative_calculation.py#L703) -- which is feeding in `lambda_protocol=LambdaProtocol()`. We should leave `lambda_protocol=None` here so that the `HybridRepexSampler` can automatically determine which protocol to use as it does [here](https://github.com/choderalab/perses/blob/main/perses/samplers/multistate.py#L44-L51).
