### ISSUE TITLE
Enable only solvent phase to be specified

### ISSUE THREAD

**Issue by jchodera** [choderalab/perses#1117]
Omitting the `complex` phase from the YAML file generates this error:
```
2022-10-15 17:36:29,566:(0.00s):root:Box dimensions: None and None
2022-10-15 17:36:29,566:(0.00s):relative_setup:			_hmass: 3 Da.

Traceback (most recent call last):
  File "/lila/home/chodera/miniconda/envs/perses-0.11.0-preview/bin/perses-cli", line 8, in <module>
    sys.exit(cli())
  File "/lila/home/chodera/miniconda/envs/perses-0.11.0-preview/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/lila/home/chodera/miniconda/envs/perses-0.11.0-preview/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/lila/home/chodera/miniconda/envs/perses-0.11.0-preview/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/lila/home/chodera/miniconda/envs/perses-0.11.0-preview/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/lila/home/chodera/miniconda/envs/perses-0.11.0-preview/lib/python3.10/site-packages/perses/app/cli.py", line 109, in cli
    run(yaml_filename=yaml, override_string=override)
  File "/lila/home/chodera/miniconda/envs/perses-0.11.0-preview/lib/python3.10/site-packages/perses/app/setup_relative_calculation.py", line 823, in run
    setup_dict = run_setup(setup_options)
  File "/lila/home/chodera/miniconda/envs/perses-0.11.0-preview/lib/python3.10/site-packages/perses/app/setup_relative_calculation.py", line 520, in run_setup
    fe_setup = RelativeFEPSetup(ligand_file, old_ligand_index, new_ligand_index, forcefield_files,phases=phases,
  File "/lila/home/chodera/miniconda/envs/perses-0.11.0-preview/lib/python3.10/site-packages/perses/app/relative_setup.py", line 206, in __init__
    assert 'complex' in phases, f"cannot use deterministic atom placement if complex is not in the specified phases to generate"
AssertionError: cannot use deterministic atom placement if complex is not in the specified phases to generate
```
It would be useful if our refactoring could permit use of the `solvent` phase on its own.

**Comment by mikemhenry** [comment]
Looks like we have that as a todo :)
https://github.com/choderalab/perses/blob/main/perses/app/relative_setup.py#L207
