### ISSUE TITLE
Nans in the first step of an Non-eq. cycling calculation (across a mutation)

### ISSUE THREAD

**Issue by sukritsingh** [choderalab/perses#1119]
Hi! 

I've been setting up a few mutants to study the impact of a mutation in the context of a dimerization, and I have encountered a mutation case that appears to fail? It is an ILE->ASP mutation.

I've attached a tarball here of the setup files + the scripts used. 
[ripk2-failure-case.tar.gz](https://github.com/choderalab/perses/files/9833660/ripk2-failure-case.tar.gz)

The three python scripts are run as shown in the `run_scripts.sh`. For both Apo and Complex phase, the HTF setup seems to work(`setup_mutation_htf.py`), or at least ends with no error reportings/warnings. However, upon trying to do non-equilibrium cycling (`run_neq.py`) it instantly fails with the following stack trace within the first step (also documented in `log.failure`):
```
WARNING:root:Warning: importing 'simtk.openmm' is deprecated.  Import 'openmm' instead.
DEBUG:root:Step: 0, Equilibrating at lambda = 0, Elapsed time: 0.020032151540120443 minutes
Traceback (most recent call last):
  File "/lila/data/chodera/sukrit/ripk2/perses/lilac-setup/i307d/scripts/run_neq_complex.py", line 129, in <module>
    integrator.step(1)
  File "/home/singhs15/miniconda3/envs/dev-perses/lib/python3.10/site-packages/openmm/openmm.py", line 6011, in step
    return _openmm.CustomIntegrator_step(self, steps)
openmm.OpenMMException: Particle coordinate is nan
```

I have used this exact scripts for three other mutations on this system: SER->ASP, GLU->LYS (in 2 different GLU positions) all of which have run successfully 1 cycle to completion. In another protein system I have been able to use these scripts to do a neutral->charged residue mutation (GLY->ARG) without fail so I'm not too sure what the issue might be here?

After chatting with @ijpulidos I tried running the minimization with larger tolerance (increased by 10X) or using the `FIREMinimizationIntegrator` and both cases showed the exact same behavior for me.

Any advice as to what to do? I took a look at the start and end PDB files and everything seemed okay for me there too so I'm not too sure how to progress.

**Comment by ijpulidos** [comment]
Thanks for the feedback @sukritsingh 

I can reproduce your issue. I will have to take a deeper look into it to see if I can spot something. At a first glance everything seems okay.

**Comment by zhang-ivy** [comment]
>Any advice as to what to do?

I would try to see if you can run vanilla MD with the ommtools langevin integrator (or the omm langevin middle integrator) with the perses-generated hybrid system for that mutation -- and see if you are getting nans. If you are, then there may be an instability in the hybrid system.

**Comment by jchodera** [comment]
@sukritsingh : In `run_scripts.sh`, you call `run_neq_complex.py`, but you only packaged a script called `run_neq.py`. Did you forget to include the right script?

**Comment by jchodera** [comment]
Minimization is super tricky with the `PeriodicNonequilibriumIntegrator`. 

First, you want to make sure you're minimizing enough, or else you could NaN quickly. Did you try minimizing without overriding `tolerance`?
```
# Minimize
# openmm.LocalEnergyMinimizer.minimize(context)
openmm.LocalEnergyMinimizer.minimize(context, tolerance=100)
```
Second, it's important to remember how the `PeriodicNonequilibriumIntegrator` works: 
* At step 0, the integrator resets, clearing work accumulators and resetting the global parameters to the values dictated by the alchemical functions for lambda=0.
* In subsequent steps, it updates the global parameters tracking the value of lambda

This means that if the default global parameters are not all set to _exactly_ match the initial values that are set by `lambda=0` in the alchemical functions, you will immediately get a NaN. 

Because of this, we provide a convenience function `.reset()`, which will put the context global parameters to the correct state for lambda=0.

I'd suggest adding `integrator.reset()` before minimization and see if this makes any difference.

**Comment by sukritsingh** [comment]
> In run_scripts.sh, you call run_neq_complex.py, but you only packaged a script called run_neq.py. Did you forget to include the right script?

When I packaged my example case I renamed `run_neq_complex.py` to `run_neq.py` but forgot to update `run_scripts.sh` - they are the same script! Sorry about the confusion.

> Did you try minimizing without overriding tolerance?
Yep! The first line `openmm.LocalEnergyMinimizer.minimize(context)` was what worked for all other mutation cases. When it failed in this case I tried overriding the tolerance to different values when running (I read that the default was 10 so I went as high as `tolerance=100`), all of which ended up in the same crash when running `run_neq.py`

Thanks for all the suggestions @zhang-ivy and @jchodera! I'll try out the following and report back:
1. Run the hybrid system with omm langevin middle integrator or ommtools langevin middle integrator and see if either of those work
2. Try including an `integrator.reset()` before minimization and see if that works.

**Comment by zhang-ivy** [comment]
>The first line openmm.LocalEnergyMinimizer.minimize(context) was what worked for all other mutation cases. When it failed in this case I tried overriding the tolerance to different values when running (I read that the default was 10 so I went as high as tolerance=100), all of which ended up in the same crash when running run_neq.py

What are you setting `maxIterations` equal to? Try setting it to 0 if it isn't already set to that. From the openmm docs:
```
minimation is continued until the results converge without regard to how many iterations it takes.
```

If your maxIterations is too low, changing the tolerance may not be helping in the way we would expect it to

**Comment by sukritsingh** [comment]
>What are you setting maxIterations equal to? Try setting it to 0 if it isn't already set to that. From the openmm docs:

I used the default `maxIterations=0` based on the documentation for [LocalEnergyMinimizer for 7.7](http://docs.openmm.org/latest/api-python/generated/openmm.openmm.LocalEnergyMinimizer.html?highlight=localenergyminimizer)

**Comment by sukritsingh** [comment]
Update on debugging attempts:
1. Sadly, `integrator.reset()` did not alleviate this issue. After discussing with @jchodera I had my script output the energy values before and after minimization + write out a state,system, and integrator files after minimization. 
From the script print statement:
```
Initial E: 95796110512784.81 kJ/mol
Final : -1662331.9115387665 kJ/mol
```

I think it's promising that the minimization finished and gave a negative (not crazy) value for a dimeric protein system? Not too sure what to make of the initial value honestly.
 
The `state`, `system`, and `integrator.xml` are attached below in the tarball, along with the version of the script used to write out energies and save files:
[ripk2-failure-xml-files.tar.gz](https://github.com/choderalab/perses/files/9854880/ripk2-failure-xml-files.tar.gz)

Note that in this tarball is also sample PDB files (`complex_old.pdb`, `complex_new.pdb` generated during `setup_mutation_htf.py` from my initial post).

2. Testing with OpenMM `LangevinMiddleIntegrator` and OpenMMTool's `LangevinIntegrator` both didn't work. The integrators both crashed giving a `openmm.OpenMMException: std::bad_cast` error. Full stack trace below:

OpenMMTools `LangevinIntegrator`:
```
Traceback (most recent call last):
  File "/lila/data/chodera/sukrit/ripk2/perses/lilac-setup/i307d/scripts/run_neq_complex_save_debug.py", line 146, in <module>
    integrator.reset()
  File "/home/singhs15/miniconda3/envs/dev-perses/lib/python3.10/site-packages/openmmtools/integrators.py", line 1807, in reset
    super(AlchemicalNonequilibriumLangevinIntegrator, self).reset()
  File "/home/singhs15/miniconda3/envs/dev-perses/lib/python3.10/site-packages/openmmtools/integrators.py", line 1652, in reset
    self.reset_protocol_work()
  File "/home/singhs15/miniconda3/envs/dev-perses/lib/python3.10/site-packages/openmmtools/integrators.py", line 1600, in reset_protocol_work
    self.setGlobalVariableByName("protocol_work", 0)
  File "/home/singhs15/miniconda3/envs/dev-perses/lib/python3.10/site-packages/openmm/openmm.py", line 5697, in setGlobalVariableByName
    return _openmm.CustomIntegrator_setGlobalVariableByName(self, name, value)
openmm.OpenMMException: std::bad_cast
```
OpenMM's `LangevinMiddleIntegrator`:
```
Traceback (most recent call last):
  File "/lila/data/chodera/sukrit/ripk2/perses/lilac-setup/i307d/scripts/run_neq_complex_save_debug.py", line 151, in <module>
    integrator.reset()
  File "/home/singhs15/miniconda3/envs/dev-perses/lib/python3.10/site-packages/openmmtools/integrators.py", line 1807, in reset
    super(AlchemicalNonequilibriumLangevinIntegrator, self).reset()
  File "/home/singhs15/miniconda3/envs/dev-perses/lib/python3.10/site-packages/openmmtools/integrators.py", line 1652, in reset
    self.reset_protocol_work()
  File "/home/singhs15/miniconda3/envs/dev-perses/lib/python3.10/site-packages/openmmtools/integrators.py", line 1600, in reset_protocol_work
    self.setGlobalVariableByName("protocol_work", 0)
  File "/home/singhs15/miniconda3/envs/dev-perses/lib/python3.10/site-packages/openmm/openmm.py", line 5697, in setGlobalVariableByName
    return _openmm.CustomIntegrator_setGlobalVariableByName(self, name, value)
openmm.OpenMMException: std::bad_cast
```

These were generated using versions of the same script I attached above in # 1. The lines used to generate the integrators have been commented out (named as `ez_integrator`)

**Comment by sukritsingh** [comment]
Here's the transformation that was output during mutation setup (requested by @zhang-ivy )
![transformation](https://user-images.githubusercontent.com/8420446/197621002-a8299838-6a2f-420c-917f-b3f280337758.png)

**Comment by zhang-ivy** [comment]
Hmm ok the next thing I would do is print out the energies before and after the first step of MD and see if you can figure out which atom(s) are causing the energy to explode -- let me know if you need pointers on how to implement this!

**Comment by sukritsingh** [comment]
On a whim after someone mentioned HMR, I decided to try halving the timestep used for (in the script I changed `timestep=2.0`). That works! The whole system ran a full forward and reverse non-eq. cycle (with equilibrations). 

Worth noting that these systems were all run with a `hydrogenMass=3.0` (the default in Perses). This supports the idea that there's some inherent instability in the system rather than anything *wrong* per se, especially since other mutations were run with 4 fs timesteps.

> print out the energies before and after the first step of MD and see if you can figure out which atom(s) are causing the energy to explode -- let me know if you need pointers on how to implement this!

Good idea! Do you have any sample code or something I can quickly use to identify this? If not that's fine just don't want to reinvent the wheel if this is a debugging process y'all have dealt with before.

**Comment by zhang-ivy** [comment]
You'll actually want to check the positions (and also maybe the forces and energy) before and after running the first step of MD. Here is some sample code that you can adapt: 

```
energies_md, positions_md, states_md = [], [], []
for _ in range(250):
    integrator.step(1)
    state_md = context.getState(getEnergy=True, getPositions=True, getForces=True)
    energy = state_md.getPotentialEnergy()
    pos = state_md.getPositions(asNumpy=True)
    states_md.append(state_md)
    energies_md.append(energy)
    positions_md.append(pos)

# Check to see if any of the values in the first frame are nan
np.isnan(positions_md[0].value_in_unit_system(unit.md_unit_system)).any()

# Check the forces 
for i, force in enumerate(states_md[0].getForces(asNumpy=True)):
    print(i, force)
```

**Comment by sukritsingh** [comment]
I can't attach the files due to size but after a few iterations of running for 250 steps (like in your example above), letting it crash (usually ~90-130 steps), and identifying the atoms with the highest forces that blew up, I noticed that it was consistently one of the water molecules that were experiencing too high a force and were then blowing up. I tried seeing if the water in question was close to any protein that may inform this and it wasn't. Any insight on what to make of this? 

The only thought I had was when I revisited the code for [relative point mutation setup ](https://github.com/choderalab/perses/blob/0.10.1/perses/app/relative_point_mutation_setup.py#L134) I noticed in `forcefield_kwargs` that `rigidWater=True` isn't included. 

In the[ OpenMM docs](http://docs.openmm.org/latest/userguide/application/02_running_sims.html) it says:
```
OpenMM makes water molecules completely rigid, constraining both their bond lengths and angles. You can disable this behavior with the rigidWater parameter

system = prmtop.createSystem(nonbondedMethod=NoCutoff, constraints=None, rigidWater=False)

Be aware that flexible water may require you to further reduce the integration step size, typically to about 0.5 fs.
```

I don't remember if `rigidWater=True` is the default in OpenMM system creation, but if it's not, could this explain some of the instability I am seeing?

**Comment by zhang-ivy** [comment]
Interesting.. I'm pretty sure rigidWater defaults to True based on this conversation: https://github.com/openmm/openmm/issues/3323

But I'm not sure what else might be causing the instability...
