### ISSUE TITLE
SmallMoleculeSetProposalEngine does not preserve _periodicBoxVectors

### ISSUE THREAD

**Issue by jchodera** [choderalab/perses#119]
Unlike the `PointMutationProposalEngine`, `SmallMoleculeSetProposalEngine` creates a new `Topology` from scratch, and in doing so omits copying some critical information, like `_periodicBoxVectors`.  This leads to errors like
```
======================================================================
ERROR: Testing expanded ensemble sampler with T4LysozymeInhibitorsTestSystem 'explicit'
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/choderaj/github/choderalab/perses/perses.choderalab/perses/samplers/samplers.py", line 701, in run
    self.update()
  File "/Users/choderaj/github/choderalab/perses/perses.choderalab/perses/samplers/samplers.py", line 688, in update
    self.update_sampler()
  File "/Users/choderaj/github/choderalab/perses/perses.choderalab/perses/samplers/samplers.py", line 607, in update_sampler
    topology_proposal = self.proposal_engine.propose(system, topology)
  File "/Users/choderaj/github/choderalab/perses/perses.choderalab/perses/rjmc/topology_proposal.py", line 922, in propose
    new_system = self._system_generator.build_system(new_topology)
  File "/Users/choderaj/github/choderalab/perses/perses.choderalab/perses/rjmc/topology_proposal.py", line 858, in build_system
    raise Exception(msg)
Exception: Requested periodic boundary conditions for a Topology that does not specify periodic box dimensions
```
I will add a quick fix in #116, but we might want to rejigger the way that the new `Topology` is constructed to instead use `Modeller` to delete/add atoms to protect ourselves from future changes.  @pgrinaway might want to coordinate with @juliebehr about how best to handle this.

**Comment by jchodera** [comment]
This was quick-fixed in #116, so closing for now.
