### ISSUE TITLE
parmed.exceptions.MoleculeError: 4-atom term cannot have duplicate atoms

### ISSUE THREAD

**Issue by jchodera** [choderalab/perses#141]
Just noticed this error with the kinase inhibitors testsystem:
```
================================================================================
SAMS sampler iteration     1
--------------------------------------------------------------------------------
Expanded Ensemble sampler iteration        1
................................................................................
MCMC sampler iteration 1
Taking 2500 steps of GHMC...
Final energy is     -437.353 kT
................................................................................
Updating chemical state with ncmc-geometry-ncmc scheme...
Proposing new topology...
Proposed transformation: Cc1cccc(c1NC(=O)c2cnc(s2)Nc3cc(nc(n3)C)N4CCN(CC4)CCO)Cl => Cc1c2c(c(n(c1=O)C)Nc3ccc(cc3F)I)c(=O)n(c(=O)n2c4cccc(c4)NC(=O)C)C5CC5
Generating new system...
Performing NCMC annihilation
LOG: Creating alchemically modified system...
LOG: Elapsed time 0.045 s.
LOG: Creating alchemically modified intermediate...
LOG: Elapsed time 0.034 s.
LOG: NCMC logP     +270.3 | initial_total_energy     -891.8 kT | final_total_energy    -1566.1 kT.
Geometry engine proposal...
Traceback (most recent call last):
  File "perses/tests/testsystems.py", line 792, in <module>
    run_kinase_inhibitors()
  File "perses/tests/testsystems.py", line 789, in run_kinase_inhibitors
    testsystem.sams_samplers[environment].run(niterations=1000)
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/perses-0.1-py2.7.egg/perses/samplers/samplers.py", line 921, in run
    self.update()
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/perses-0.1-py2.7.egg/perses/samplers/samplers.py", line 905, in update
    self.update_sampler()
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/perses-0.1-py2.7.egg/perses/samplers/samplers.py", line 873, in update_sampler
    self.sampler.update()
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/perses-0.1-py2.7.egg/perses/samplers/samplers.py", line 751, in update
    self.update_state()
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/perses-0.1-py2.7.egg/perses/samplers/samplers.py", line 692, in update_state
    geometry_new_positions, geometry_logp_propose  = self.geometry_engine.propose(topology_proposal, geometry_old_positions, self.sampler.thermodynamic_state.beta)
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/perses-0.1-py2.7.egg/perses/rjmc/geometry.py", line 95, in propose
    logp_proposal, new_positions = self._logp_propose(top_proposal, current_positions, beta, direction='forward')
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/perses-0.1-py2.7.egg/perses/rjmc/geometry.py", line 154, in _logp_propose
    atom_proposal_order, logp_choice = proposal_order_tool.determine_proposal_order(direction='forward')
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/perses-0.1-py2.7.egg/perses/rjmc/geometry.py", line 858, in determine_proposal_order
    structure = parmed.openmm.load_topology(self._topology_proposal.new_topology, self._topology_proposal.new_system)
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/parmed/utils/decorators.py", line 31, in new_fcn
    return fcn(*args, **kwargs)
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/parmed/openmm/topsystem.py", line 164, in load_topology
    _process_dihedral(struct, force)
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/parmed/openmm/topsystem.py", line 270, in _process_dihedral
    type=dihed_type))
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/parmed/topologyobjects.py", line 1995, in __init__
    _FourAtomTerm.__init__(self, atom1, atom2, atom3, atom4)
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/parmed/topologyobjects.py", line 162, in __init__
    raise MoleculeError('4-atom term cannot have duplicate atoms')
parmed.exceptions.MoleculeError: 4-atom term cannot have duplicate atoms
```

**Comment by jchodera** [comment]
I've added a more detailed exception message and can confirm that I'm seeing torsions with duplicate atoms in the small molecule case:
```
================================================================================
SAMS sampler iteration     0
--------------------------------------------------------------------------------
Expanded Ensemble sampler iteration        0
................................................................................
MCMC sampler iteration 0
Taking 2500 steps of Langevin dynamics...
Final energy is     -435.504 kT
................................................................................
Updating chemical state with ncmc-geometry-ncmc scheme...
Proposing new topology...
Proposed transformation: Cc1cccc(c1NC(=O)c2cnc(s2)Nc3cc(nc(n3)C)N4CCN(CC4)CCO)Cl => Cc1c2c(c(n(c1=O)C)Nc3ccc(cc3F)I)c(=O)n(c(=O)n2c4cccc(c4)NC(=O)C)C5CC5
Generating new system...
Performing NCMC annihilation
LOG: Creating alchemically modified system...
LOG: Elapsed time 0.055 s.
LOG: Creating alchemically modified intermediate...
LOG: Elapsed time 0.011 s.
LOG: NCMC logP     +269.0 | initial_total_energy     -894.7 kT | final_total_energy    -1565.6 kT.
Geometry engine proposal...
Traceback (most recent call last):
  File "perses/tests/testsystems.py", line 792, in <module>
    run_kinase_inhibitors()
  File "perses/tests/testsystems.py", line 789, in run_kinase_inhibitors
    testsystem.sams_samplers[environment].run(niterations=1000)
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/perses-0.1-py2.7.egg/perses/samplers/samplers.py", line 922, in run
    self.update()
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/perses-0.1-py2.7.egg/perses/samplers/samplers.py", line 906, in update
    self.update_sampler()
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/perses-0.1-py2.7.egg/perses/samplers/samplers.py", line 874, in update_sampler
    self.sampler.update()
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/perses-0.1-py2.7.egg/perses/samplers/samplers.py", line 752, in update
    self.update_state()
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/perses-0.1-py2.7.egg/perses/samplers/samplers.py", line 693, in update_state
    geometry_new_positions, geometry_logp_propose  = self.geometry_engine.propose(topology_proposal, geometry_old_positions, self.sampler.thermodynamic_state.beta)
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/perses-0.1-py2.7.egg/perses/rjmc/geometry.py", line 96, in propose
    logp_proposal, new_positions = self._logp_propose(top_proposal, current_positions, beta, direction='forward')
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/perses-0.1-py2.7.egg/perses/rjmc/geometry.py", line 157, in _logp_propose
    atom_proposal_order, logp_choice = proposal_order_tool.determine_proposal_order(direction='forward')
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/perses-0.1-py2.7.egg/perses/rjmc/geometry.py", line 859, in determine_proposal_order
    raise Exception('Torsion index %d of self._topology_proposal.new_system has duplicate atoms: %d %d %d %d' % (index,i,j,k,l))
Exception: Torsion index 89 of self._topology_proposal.new_system has duplicate atoms: 20 21 22 20
```
Trying to track down where this is happening.  I suspect this may actually be due to the `gaffTemplateGenerator`.

**Comment by jchodera** [comment]
I found a good example:
```
================================================================================
SAMS sampler iteration     2
--------------------------------------------------------------------------------
Expanded Ensemble sampler iteration        2
................................................................................
MCMC sampler iteration 2
Taking 50 steps of Langevin dynamics...
Final energy is 10198352670018720.000 kT
................................................................................
Updating chemical state with ncmc-geometry-ncmc scheme...
Proposing new topology...
proposed SMILES string: Cc1c2c(c(n(c1=O)C)Nc3ccc(cc3F)I)c(=O)n(c(=O)n2c4cccc(c4)NC(=O)C)C5CC5
LOG: MOL
LOG: MOL
Traceback (most recent call last):
  File "perses/tests/testsystems.py", line 804, in <module>
    run_kinase_inhibitors()
  File "perses/tests/testsystems.py", line 789, in run_kinase_inhibitors
    testsystem.sams_samplers[environment].run(niterations=5)
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/perses-0.1-py2.7.egg/perses/samplers/samplers.py", line 924, in run
    self.update()
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/perses-0.1-py2.7.egg/perses/samplers/samplers.py", line 908, in update
    self.update_sampler()
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/perses-0.1-py2.7.egg/perses/samplers/samplers.py", line 876, in update_sampler
    self.sampler.update()
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/perses-0.1-py2.7.egg/perses/samplers/samplers.py", line 754, in update
    self.update_state()
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/perses-0.1-py2.7.egg/perses/samplers/samplers.py", line 650, in update_state
    topology_proposal = self.proposal_engine.propose(system, topology)
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/perses-0.1-py2.7.egg/perses/rjmc/topology_proposal.py", line 939, in propose
    new_system = self._system_generator.build_system(new_topology)
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/perses-0.1-py2.7.egg/perses/rjmc/topology_proposal.py", line 862, in build_system
    check_system(system)
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/perses-0.1-py2.7.egg/perses/tests/utils.py", line 536, in check_system
    raise Exception(msg)
Exception: Torsion index 89 of self._topology_proposal.new_system has duplicate atoms: 20 21 22 20
Serialzed system to system.xml for inspection.
```
The SMILES string is `Cc1c2c(c(n(c1=O)C)Nc3ccc(cc3F)I)c(=O)n(c(=O)n2c4cccc(c4)NC(=O)C)C5CC5`, which does have a [three-carbon ring](http://www.chemicalize.org/structure/#!mol=Cc1c2c%28c%28n%28c1%3DO%29C%29Nc3ccc%28cc3F%29I%29c%28%3DO%29n%28c%28%3DO%29n2c4cccc%28c4%29NC%28%3DO%29C%29C5CC5&source=fp) in it.

I'll report this to `parmed`.

**Comment by jchodera** [comment]
This should be resolved thanks to the OpenMM and ParmEd PRs.
