### ISSUE TITLE
ValueError: 'CN(C)C/C=C/C(=O)Nc1cc2c(cc1OC3CCOC3)ncnc2Nc4ccc(c(c4)Cl)F' is not in list

### ISSUE THREAD

**Issue by jchodera** [choderalab/perses#155]
When I run the `run_kinase_inhibitors()` test from `perses.tests.testsystems`, I see errors like:
```
================================================================================
SAMS sampler iteration     3
--------------------------------------------------------------------------------
Expanded Ensemble sampler iteration        3
................................................................................
MCMC sampler iteration 3
Taking 50 steps of Langevin dynamics...
Final energy is 78926729089.997 kT
................................................................................
Updating chemical state with ncmc-geometry-ncmc scheme...
Proposing new topology...
Traceback (most recent call last):
  File "perses/tests/testsystems.py", line 804, in <module>
    run_kinase_inhibitors()
  File "perses/tests/testsystems.py", line 789, in run_kinase_inhibitors
    testsystem.sams_samplers[environment].run(niterations=5)
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/perses-0.1-py2.7.egg/perses/samplers/samplers.py", line 924, in run
    self.update()
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/perses-0.1-py2.7.egg/perses/samplers/samplers.py", line 908, in update
    self.update_sampler()
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/perses-0.1-py2.7.egg/perses/samplers/samplers.py", line 876, in update_sampler
    self.sampler.update()
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/perses-0.1-py2.7.egg/perses/samplers/samplers.py", line 754, in update
    self.update_state()
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/perses-0.1-py2.7.egg/perses/samplers/samplers.py", line 650, in update_state
    topology_proposal = self.proposal_engine.propose(system, topology)
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/perses-0.1-py2.7.egg/perses/rjmc/topology_proposal.py", line 927, in propose
    current_mol_smiles)
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/perses-0.1-py2.7.egg/perses/rjmc/topology_proposal.py", line 1228, in _propose_molecule
    current_smiles_idx = self._smiles_list.index(molecule_smiles)
ValueError: 'CN(C)C/C=C/C(=O)Nc1cc2c(cc1OC3CCOC3)ncnc2Nc4ccc(c(c4)Cl)F' is not in list
```
This might just be a repeat of the stereochemistry problems from #120, since I notice a double bond in this failure.

**Comment by pgrinaway** [comment]
Closing because of duplication for #120. It's better to just solve the stereochem issue altogether.
