### ISSUE TITLE
UnboundLocalError: local variable 'proposal_order_forward' referenced before assignment

### ISSUE THREAD

**Issue by jchodera** [choderalab/perses#183]
Here's [an error I haven't seen before](https://travis-ci.org/choderalab/perses/jobs/118608035#L876-L909):
```
======================================================================
FAIL: Doctest: perses.samplers.samplers.SAMSSampler
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/_test/lib/python2.7/doctest.py", line 2226, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for perses.samplers.samplers.SAMSSampler
  File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/perses-0.1-py2.7.egg/perses/samplers/samplers.py", line 831, in SAMSSampler
----------------------------------------------------------------------
File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/perses-0.1-py2.7.egg/perses/samplers/samplers.py", line 877, in perses.samplers.samplers.SAMSSampler
Failed example:
    sams_sampler.run()
Exception raised:
    Traceback (most recent call last):
      File "/home/travis/miniconda/envs/_test/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest perses.samplers.samplers.SAMSSampler[13]>", line 1, in <module>
        sams_sampler.run()
      File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/perses-0.1-py2.7.egg/perses/samplers/samplers.py", line 969, in run
        self.update()
      File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/perses-0.1-py2.7.egg/perses/samplers/samplers.py", line 953, in update
        self.update_sampler()
      File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/perses-0.1-py2.7.egg/perses/samplers/samplers.py", line 921, in update_sampler
        self.sampler.update()
      File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/perses-0.1-py2.7.egg/perses/samplers/samplers.py", line 796, in update
        self.update_state()
      File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/perses-0.1-py2.7.egg/perses/samplers/samplers.py", line 735, in update_state
        geometry_logp_reverse = self.geometry_engine.logp_reverse(topology_proposal, geometry_new_positions, geometry_old_positions, self.sampler.thermodynamic_state.beta)
      File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/perses-0.1-py2.7.egg/perses/rjmc/geometry.py", line 138, in logp_reverse
        logp_proposal, _ = self._logp_propose(top_proposal, old_coordinates, beta, new_positions=new_coordinates, direction='reverse')
      File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/perses-0.1-py2.7.egg/perses/rjmc/geometry.py", line 318, in _logp_propose
        logging.log(logging.DEBUG, "Proposal order time: %f s | Proposal order forward: %f s | Growth system generation: %f s | Total torsion scan time %f s | Total energy computation time %f s | Position set time %f s| Total time %f s" % (proposal_order_time, proposal_order_forward, growth_system_time , self._torsion_coordinate_time, self._energy_time, self._position_set_time, total_time))
    UnboundLocalError: local variable 'proposal_order_forward' referenced before assignment
```

**Comment by pgrinaway** [comment]
Fixed in #186
