### ISSUE TITLE
FloatingPointError: underflow encountered in exp

### ISSUE THREAD

**Issue by jchodera** [choderalab/perses#184]
I'm still seeing [these underflow errors](https://travis-ci.org/choderalab/perses/jobs/118611253#L2162-L2178):
```
======================================================================
ERROR: Make sure logp_reverse and logp_forward are consistent
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/perses-0.1-py2.7.egg/perses/tests/test_geometry_engine.py", line 554, in test_logp_reverse
    new_positions, logp_proposal = geometry_engine.propose(sm_top_proposal, pos1, beta)
  File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/perses-0.1-py2.7.egg/perses/rjmc/geometry.py", line 109, in propose
    logp_proposal, new_positions = self._logp_propose(top_proposal, current_positions, beta, direction='forward')
  File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/perses-0.1-py2.7.egg/perses/rjmc/geometry.py", line 288, in _logp_propose
    phi, logp_phi = self._propose_torsion(context, torsion, new_positions, r, theta, beta, n_divisions=360)
  File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/perses-0.1-py2.7.egg/perses/rjmc/geometry.py", line 824, in _propose_torsion
    logp_torsions, phis = self._torsion_log_pmf(growth_context, torsion, positions, r, theta, beta, n_divisions=n_divisions)
  File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/perses-0.1-py2.7.egg/perses/rjmc/geometry.py", line 791, in _torsion_log_pmf
    q = np.exp(logq)
FloatingPointError: underflow encountered in exp
```

**Comment by pgrinaway** [comment]
Fixed in #186
