### ISSUE TITLE
TypeError: No matching definition for argument type(s) array(float32, 1d, C), array(float32, 1d, C), array(float32, 1d, C), array(float64, 1d, C)

### ISSUE THREAD

**Issue by jchodera** [choderalab/perses#185]
This error [seems to be new to me](https://travis-ci.org/choderalab/perses/jobs/118611253#L2162-L2178):
```
======================================================================
ERROR: for each torsion, calculate position of atom1
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/perses-0.1-py2.7.egg/perses/tests/test_geometry_engine.py", line 439, in test_existing_coordinates
    recalculated_atom1_position, _ = geometry_engine._internal_to_cartesian(atom2_position, atom3_position, atom4_position, internal_coordinates[0], internal_coordinates[1], internal_coordinates[2])
  File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/perses-0.1-py2.7.egg/perses/rjmc/geometry.py", line 640, in _internal_to_cartesian
    xyz = coordinate_numba.internal_to_cartesian(bond_position, angle_position, torsion_position, np.array([r, theta, phi], dtype=np.float64))
  File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/numba/dispatcher.py", line 320, in _explain_matching_error
    raise TypeError(msg)
TypeError: No matching definition for argument type(s) array(float32, 1d, C), array(float32, 1d, C), array(float32, 1d, C), array(float64, 1d, C)
```

**Comment by pgrinaway** [comment]
Addressed in #186
