### ISSUE TITLE
More test failures from Jenkins

### ISSUE THREAD

**Issue by jchodera** [choderalab/perses#188]
I have jenkins running the `perses-dev` builds now, and there are a number of other test failures that have shown up:
https://jenkins.choderalab.org/job/test-perses-linux-xeon-gtxtitan-src/5/console

Would be good to go through these and carve them out into individual issues for us to address.

For example, I'm puzzled by failures like this one:

```
======================================================================
ERROR: Testing expanded ensemble sampler with AlkanesTestSystem 'explicit'
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jenkins/workspace/test-perses-linux-xeon-gtxtitan-src/miniconda/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/jenkins/workspace/test-perses-linux-xeon-gtxtitan-src/miniconda/lib/python2.7/site-packages/perses-0.1-py2.7.egg/perses/samplers/samplers.py", line 820, in run
    self.update()
  File "/home/jenkins/workspace/test-perses-linux-xeon-gtxtitan-src/miniconda/lib/python2.7/site-packages/perses-0.1-py2.7.egg/perses/samplers/samplers.py", line 799, in update
    self.update_state()
  File "/home/jenkins/workspace/test-perses-linux-xeon-gtxtitan-src/miniconda/lib/python2.7/site-packages/perses-0.1-py2.7.egg/perses/samplers/samplers.py", line 684, in update_state
    topology_proposal = self.proposal_engine.propose(system, topology)
  File "/home/jenkins/workspace/test-perses-linux-xeon-gtxtitan-src/miniconda/lib/python2.7/site-packages/perses-0.1-py2.7.egg/perses/rjmc/topology_proposal.py", line 1079, in propose
    current_mol_smiles)
  File "/home/jenkins/workspace/test-perses-linux-xeon-gtxtitan-src/miniconda/lib/python2.7/site-packages/perses-0.1-py2.7.egg/perses/rjmc/topology_proposal.py", line 1414, in _propose_molecule
    current_smiles_idx = self._smiles_list.index(molecule_smiles)
ValueError: 'CC' is not in list
```

**Comment by pgrinaway** [comment]
I think Jenkins is dead (long live Jenkins?) for now, so I'm closing this in favor of #248 . We can discuss more about how to best go about testing there.
