### ISSUE TITLE
test_geometry_engine nosetest failure

### ISSUE THREAD

**Issue by jchodera** [choderalab/perses#19]
Does this fail on your system?
```
======================================================================
ERROR: Run the geometry engine a few times to make sure that it actually runs
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/choderaj/github/choderalab/perses/perses.jchodera/perses/tests/test_geometry_engine.py", line 74, in test_run_geometry_engine
    new_to_old_atom_mapping = align_molecules(molecule1, molecule2)
  File "/Users/choderaj/github/choderalab/perses/perses.jchodera/perses/tests/test_geometry_engine.py", line 56, in align_molecules
    match = matches[0]
TypeError: 'OEMatchBaseIter' object does not support indexing
```

**Comment by pgrinaway** [comment]
Hm, looks like I didn't commit a fix to that. I'll file a quick PR as soon as I get in

**Comment by jchodera** [comment]
Also these:
```
======================================================================
FAIL: Doctest: perses.annihilation.alchemical_engine.AlchemicalEliminationEngine
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/choderaj/anaconda/lib/python2.7/doctest.py", line 2226, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for perses.annihilation.alchemical_engine.AlchemicalEliminationEngine
  File "/Users/choderaj/anaconda/lib/python2.7/site-packages/perses-0.1-py2.7.egg/perses/annihilation/alchemical_engine.py", line 8, in AlchemicalEliminationEngine

----------------------------------------------------------------------
File "/Users/choderaj/anaconda/lib/python2.7/site-packages/perses-0.1-py2.7.egg/perses/annihilation/alchemical_engine.py", line 26, in perses.annihilation.alchemical_engine.AlchemicalEliminationEngine
Failed example:
    topology_proposal = topology_proposal.TopologyProposal(old_topology=testsystem.topology, new_topology=testsystem.topology, logp=0.0, new_to_old_atom_map=new_to_old_atom_map, metadata=dict())
Exception raised:
    Traceback (most recent call last):
      File "/Users/choderaj/anaconda/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest perses.annihilation.alchemical_engine.AlchemicalEliminationEngine[4]>", line 1, in <module>
        topology_proposal = topology_proposal.TopologyProposal(old_topology=testsystem.topology, new_topology=testsystem.topology, logp=0.0, new_to_old_atom_map=new_to_old_atom_map, metadata=dict())
    TypeError: __new__() got an unexpected keyword argument 'old_topology'
----------------------------------------------------------------------
File "/Users/choderaj/anaconda/lib/python2.7/site-packages/perses-0.1-py2.7.egg/perses/annihilation/alchemical_engine.py", line 30, in perses.annihilation.alchemical_engine.AlchemicalEliminationEngine
Failed example:
    alchemical_system_insert = make_alchemical_system(testsystem.system, topology_proposal, direction='create')
Exception raised:
    Traceback (most recent call last):
      File "/Users/choderaj/anaconda/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest perses.annihilation.alchemical_engine.AlchemicalEliminationEngine[5]>", line 1, in <module>
        alchemical_system_insert = make_alchemical_system(testsystem.system, topology_proposal, direction='create')
    NameError: name 'make_alchemical_system' is not defined
----------------------------------------------------------------------
File "/Users/choderaj/anaconda/lib/python2.7/site-packages/perses-0.1-py2.7.egg/perses/annihilation/alchemical_engine.py", line 31, in perses.annihilation.alchemical_engine.AlchemicalEliminationEngine
Failed example:
    alchemical_system_delete = make_alchemical_system(testsystem.system, topology_proposal, direction='delete')
Exception raised:
    Traceback (most recent call last):
      File "/Users/choderaj/anaconda/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest perses.annihilation.alchemical_engine.AlchemicalEliminationEngine[6]>", line 1, in <module>
        alchemical_system_delete = make_alchemical_system(testsystem.system, topology_proposal, direction='delete')
    NameError: name 'make_alchemical_system' is not defined
```
The rest of the failures are mine, I think.

**Comment by pgrinaway** [comment]
Failures fixed, new failures from change of API documented in #28
