### ISSUE TITLE
GHMC NCMC

### ISSUE THREAD

**Issue by jchodera** [choderalab/perses#202]
This is just to remind us to merge in @pgrinaway's GHMC-based NCMC at some point, since it will prevent [Jenkins failures like this one](https://jenkins.choderalab.org/job/test-perses-linux-xeon-gtxtitan-src/28/console):
```
======================================================================
ERROR: Testing SAMS sampler with T4LysozymeInhibitorsTestSystem 'explicit'
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jenkins/workspace/test-perses-linux-xeon-gtxtitan-src/miniconda/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/jenkins/workspace/test-perses-linux-xeon-gtxtitan-src/miniconda/lib/python2.7/site-packages/perses-0.1-py2.7.egg/perses/samplers/samplers.py", line 972, in run
    self.update()
  File "/home/jenkins/workspace/test-perses-linux-xeon-gtxtitan-src/miniconda/lib/python2.7/site-packages/perses-0.1-py2.7.egg/perses/samplers/samplers.py", line 956, in update
    self.update_sampler()
  File "/home/jenkins/workspace/test-perses-linux-xeon-gtxtitan-src/miniconda/lib/python2.7/site-packages/perses-0.1-py2.7.egg/perses/samplers/samplers.py", line 924, in update_sampler
    self.sampler.update()
  File "/home/jenkins/workspace/test-perses-linux-xeon-gtxtitan-src/miniconda/lib/python2.7/site-packages/perses-0.1-py2.7.egg/perses/samplers/samplers.py", line 799, in update
    self.update_state()
  File "/home/jenkins/workspace/test-perses-linux-xeon-gtxtitan-src/miniconda/lib/python2.7/site-packages/perses-0.1-py2.7.egg/perses/samplers/samplers.py", line 742, in update_state
    [ncmc_new_positions, ncmc_introduction_logp, potential_insert] = self.ncmc_engine.integrate(topology_proposal, geometry_new_positions, direction='insert')
  File "/home/jenkins/workspace/test-perses-linux-xeon-gtxtitan-src/miniconda/lib/python2.7/site-packages/perses-0.1-py2.7.egg/perses/annihilation/ncmc_switching.py", line 394, in integrate
    raise NaNException("Final potential of 'delete' operation is NaN")
NaNException: Final potential of 'delete' operation is NaN
```

**Comment by pgrinaway** [comment]
Resolved in #203
