### ISSUE TITLE
forcefieldGenerator issue with Python 3.x?

### ISSUE THREAD

**Issue by jchodera** [choderalab/perses#427]
I've run into this issue, which seems to be a problem with the forcefield generators.
```
> nosetests -vv perses/tests/test_topology_proposal.py:test_small_molecule_proposals
======================================================================
ERROR: Make sure the small molecule proposal engine generates molecules
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/choderaj/miniconda3/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/Users/choderaj/github/choderalab/perses/perses.choderalab/perses/tests/test_topology_proposal.py", line 89, in test_small_molecule_proposals
    initial_system, initial_positions, initial_topology = oemol_to_omm_ff(initial_molecule, "MOL")
  File "/Users/choderaj/github/choderalab/perses/perses.choderalab/perses/tests/test_topology_proposal.py", line 70, in oemol_to_omm_ff
    system = system_generator.build_system(topology)
  File "/Users/choderaj/github/choderalab/perses/perses.choderalab/perses/rjmc/topology_proposal.py", line 1216, in build_system
    system = self._forcefield.createSystem(new_topology, **self._forcefield_kwargs)
  File "/Users/choderaj/miniconda3/lib/python3.5/site-packages/simtk/openmm/app/forcefield.py", line 1113, in createSystem
    if generator(self, res):
  File "/Users/choderaj/miniconda3/lib/python3.5/site-packages/openmoltools/forcefield_generators.py", line 504, in gaffTemplateGenerator
    molecule = generateOEMolFromTopologyResidue(residue)
  File "/Users/choderaj/miniconda3/lib/python3.5/site-packages/openmoltools/forcefield_generators.py", line 139, in generateOEMolFromTopologyResidue
    [status, output] = getstatusoutput(command)
  File "/Users/choderaj/miniconda3/lib/python3.5/subprocess.py", line 495, in getstatusoutput
    data = check_output(cmd, shell=True, universal_newlines=True, stderr=STDOUT)
  File "/Users/choderaj/miniconda3/lib/python3.5/subprocess.py", line 316, in check_output
    **kwargs).stdout
  File "/Users/choderaj/miniconda3/lib/python3.5/subprocess.py", line 385, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/Users/choderaj/miniconda3/lib/python3.5/subprocess.py", line 788, in communicate
    stdout = self.stdout.read()
  File "/Users/choderaj/miniconda3/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 34: invalid start byte
```
I'm not sure why we haven't run into this before. I don't believe the test was disabled.
I'll do more testing to see if this might be a peculiar misconfiguration of my environment.

**Comment by jchodera** [comment]
This must have been a peculiarity with my installation, since I can't replicate this on travis or another machine.
