### ISSUE TITLE
Geometry engine fails on some Mcl-1 proposals

### ISSUE THREAD

**Issue by jchodera** [choderalab/perses#501]
On the Mcl-1 example, the geometry engine sometimes fails on some proposals:
```
DEBUG:geometry:dihedrals involving new atom:
DEBUG:geometry:[<Dihedral; <Atom O1 [23057]; In MOL 7030>--<Atom C1 [23058]; In MOL 7030>--<Atom C2 [23060]; In MOL 7030>--<Atom N1 [23099]; In MOL 7030>; type=<DihedralType; phi_k=2.875, per=2, phase=180.000,  scee=1.000, scnb=1.000>>, <Dihedral; <Atom C1 [23058]; In MOL 7030>--<Atom C2 [23060]; In MOL 7030>--<Atom N1 [23099]; In MOL 7030>--<Atom C3 [23061]; In MOL 7030>; type=<DihedralType; phi_k=1.700, per=2, phase=180.000,  scee=1.000, scnb=1.000>>, <Dihedral; <Atom C1 [23058]; In MOL 7030>--<Atom C2 [23060]; In MOL 7030>--<Atom N1 [23099]; In MOL 7030>--<Atom H19 [23100]; In MOL 7030>; type=<DihedralType; phi_k=1.700, per=2, phase=180.000,  scee=1.000, scnb=1.000>>, <Dihedral; <Atom O2 [23059]; In MOL 7030>--<Atom C1 [23058]; In MOL 7030>--<Atom C2 [23060]; In MOL 7030>--<Atom N1 [23099]; In MOL 7030>; type=<DihedralType; phi_k=2.875, per=2, phase=180.000,  scee=1.000, scnb=1.000>>, <Dihedral; <Atom C2 [23060]; In MOL 7030>--<Atom N1 [23099]; In MOL 7030>--<Atom C3 [23061]; In MOL 7030>--<Atom C4 [23062]; In MOL 7030>; type=<DihedralType; phi_k=0.300, per=2, phase=180.000,  scee=1.000, scnb=1.000>>, <Dihedral; <Atom C2 [23060]; In MOL 7030>--<Atom N1 [23099]; In MOL 7030>--<Atom C3 [23061]; In MOL 7030>--<Atom C8 [23066]; In MOL 7030>; type=<DihedralType; phi_k=0.300, per=2, phase=180.000,  scee=1.000, scnb=1.000>>, <Dihedral; <Atom C3 [23061]; In MOL 7030>--<Atom N1 [23099]; In MOL 7030>--<Atom C2 [23060]; In MOL 7030>--<Atom C9 [23067]; In MOL 7030>; type=<DihedralType; phi_k=1.700, per=2, phase=180.000,  scee=1.000, scnb=1.000>>, <Dihedral; <Atom C4 [23062]; In MOL 7030>--<Atom C3 [23061]; In MOL 7030>--<Atom N1 [23099]; In MOL 7030>--<Atom H19 [23100]; In MOL 7030>; type=<DihedralType; phi_k=0.300, per=2, phase=180.000,  scee=1.000, scnb=1.000>>, <Dihedral; <Atom C5 [23063]; In MOL 7030>--<Atom C4 [23062]; In MOL 7030>--<Atom C3 [23061]; In MOL 7030>--<Atom N1 [23099]; In MOL 7030>; type=<DihedralType; phi_k=3.625, per=2, phase=180.000,  scee=1.000, scnb=1.000>>, <Dihedral; <Atom C7 [23065]; In MOL 7030>--<Atom C8 [23066]; In MOL 7030>--<Atom C3 [23061]; In MOL 7030>--<Atom N1 [23099]; In MOL 7030>; type=<DihedralType; phi_k=3.625, per=2, phase=180.000,  scee=1.000, scnb=1.000>>, <Dihedral; <Atom C8 [23066]; In MOL 7030>--<Atom C3 [23061]; In MOL 7030>--<Atom N1 [23099]; In MOL 7030>--<Atom H19 [23100]; In MOL 7030>; type=<DihedralType; phi_k=0.300, per=2, phase=180.000,  scee=1.000, scnb=1.000>>, <Dihedral; <Atom C8 [23066]; In MOL 7030>--<Atom C9 [23067]; In MOL 7030>--<Atom C2 [23060]; In MOL 7030>--<Atom N1 [23099]; In MOL 7030>; type=<DihedralType; phi_k=4.000, per=2, phase=180.000,  scee=1.000, scnb=1.000>>, <Dihedral; <Atom C9 [23067]; In MOL 7030>--<Atom C2 [23060]; In MOL 7030>--<Atom N1 [23099]; In MOL 7030>--<Atom H19 [23100]; In MOL 7030>; type=<DihedralType; phi_k=1.700, per=2, phase=180.000,  scee=1.000, scnb=1.000>>, <Dihedral; <Atom C9 [23067]; In MOL 7030>--<Atom C8 [23066]; In MOL 7030>--<Atom C3 [23061]; In MOL 7030>--<Atom N1 [23099]; In MOL 7030>; type=<DihedralType; phi_k=3.625, per=2, phase=180.000,  scee=1.000, scnb=1.000>>, <Dihedral; <Atom C10 [23068]; In MOL 7030>--<Atom C9 [23067]; In MOL 7030>--<Atom C2 [23060]; In MOL 7030>--<Atom N1 [23099]; In MOL 7030>; type=<DihedralType; phi_k=4.000, per=2, phase=180.000,  scee=1.000, scnb=1.000>>, <Dihedral; <Atom H1 [23081]; In MOL 7030>--<Atom C4 [23062]; In MOL 7030>--<Atom C3 [23061]; In MOL 7030>--<Atom N1 [23099]; In MOL 7030>; type=<DihedralType; phi_k=3.625, per=2, phase=180.000,  scee=1.000, scnb=1.000>>, <Dihedral [imp]; <Atom C1 [23058]; In MOL 7030>--<Atom C9 [23067]; In MOL 7030>--<Atom C2 [23060]; In MOL 7030>--<Atom N1 [23099]; In MOL 7030>; type=<DihedralType; phi_k=1.100, per=2, phase=180.000,  scee=1.000, scnb=1.000>>, <Dihedral [imp]; <Atom C4 [23062]; In MOL 7030>--<Atom C8 [23066]; In MOL 7030>--<Atom C3 [23061]; In MOL 7030>--<Atom N1 [23099]; In MOL 7030>; type=<DihedralType; phi_k=1.100, per=2, phase=180.000,  scee=1.000, scnb=1.000>>, <Dihedral [imp]; <Atom C2 [23060]; In MOL 7030>--<Atom C3 [23061]; In MOL 7030>--<Atom N1 [23099]; In MOL 7030>--<Atom H19 [23100]; In MOL 7030>; type=<DihedralType; phi_k=1.100, per=2, phase=180.000,  scee=1.000, scnb=1.000>>]
Traceback (most recent call last):
  File "../../scripts/setup_relative_calculation.py", line 33, in <module>
    setup_dict = relative_setup.run_setup(setup_options)
  File "/home/chodera/miniconda/lib/python3.6/site-packages/perses-0.1-py3.6.egg/perses/dispersed/relative_setup.py", line 1005, in run_setup
    solvate=solvate, atom_map=atom_map)
  File "/home/chodera/miniconda/lib/python3.6/site-packages/perses-0.1-py3.6.egg/perses/dispersed/relative_setup.py", line 215, in __init__
    beta)
  File "/home/chodera/miniconda/lib/python3.6/site-packages/perses-0.1-py3.6.egg/perses/rjmc/geometry.py", line 131, in propose
    logp_proposal, new_positions = self._logp_propose(top_proposal, current_positions, beta, direction='forward')
  File "/home/chodera/miniconda/lib/python3.6/site-packages/perses-0.1-py3.6.egg/perses/rjmc/geometry.py", line 214, in _logp_propose
    atom_proposal_order, logp_choice = proposal_order_tool.determine_proposal_order(direction='forward')
  File "/home/chodera/miniconda/lib/python3.6/site-packages/perses-0.1-py3.6.egg/perses/rjmc/geometry.py", line 1942, in determine_proposal_order
    logp_torsion_choice += add_atoms(new_heavy_atoms, atoms_torsions)
  File "/home/chodera/miniconda/lib/python3.6/site-packages/perses-0.1-py3.6.egg/perses/rjmc/geometry.py", line 1919, in add_atoms
    eligible_atoms_in_order = np.random.choice(eligible_atoms, size=len(eligible_atoms), replace=False)
  File "mtrand.pyx", line 1126, in mtrand.RandomState.choice
ValueError: a must be non-empty
```
@pgrinaway notes this could be debugged by inspecting information about the torsions used in the proposal or replacing the parmed-based torsion enumeration with a graph-based algorithm that is in the works.

Just recording this issue so we remember it.

**Comment by jchodera** [comment]
Duplicate of #508
