### ISSUE TITLE
Antechamber fails in pazopanib

### ISSUE THREAD

**Issue by hannahbrucemacdonald** [choderalab/perses#641]
We are seeing an occasional antechamber issue 

I've attached the molecule here (it's pazopanib
[pazopanib.zip](https://github.com/choderalab/perses/files/4237111/pazopanib.zip)
 from the `KinaseInhibitorsTestSystem`). I can kind of see why it's a bit confusing, because the aromaticity is across the two-ring system, but antechamber is seeing C9 as having a valency of 5... not sure if it's worth the effort

![Screen Shot 2020-02-21 at 11 52 18 AM](https://user-images.githubusercontent.com/43652597/75054203-a51f1680-54a0-11ea-9b5e-b63ae602781a.png)

I think it would be fixed if the `.mol2` generated had the (C11, N2), (N2,N4), (N4,C15), (C15,C9) bonds as `ar`, rather than [2, 1, 1, 2] respectively

>2020-02-20T14:51:24.9267903Z ======================================================================
2020-02-20T14:51:24.9269019Z ERROR: Testing KinaseInhibitorsTestSystem
2020-02-20T14:51:24.9270451Z ----------------------------------------------------------------------
2020-02-20T14:51:24.9271641Z Traceback (most recent call last):
2020-02-20T14:51:24.9273076Z   File "/usr/share/miniconda/envs/test/lib/python3.7/site-packages/nose/case.py", line 197, in runTest
2020-02-20T14:51:24.9274262Z     self.test(*self.arg)
2020-02-20T14:51:24.9276768Z   File "/home/runner/work/perses/perses/perses/tests/testsystems.py", line 2439, in checktestsystem
2020-02-20T14:51:24.9277829Z     testsystem = testsystem_class(storage_filename=storage_filename)
2020-02-20T14:51:24.9278752Z   File "/home/runner/work/perses/perses/perses/tests/testsystems.py", line 1862, in __init__
2020-02-20T14:51:24.9279675Z     super(KinaseInhibitorsTestSystem, self).__init__(**kwargs)
2020-02-20T14:51:24.9280841Z   File "/home/runner/work/perses/perses/perses/tests/testsystems.py", line 1767, in __init__
2020-02-20T14:51:24.9283128Z     modeller.addSolvent(forcefield, model='tip3p', padding=9.0*unit.angstrom)
2020-02-20T14:51:24.9284736Z   File "/usr/share/miniconda/envs/test/lib/python3.7/site-packages/simtk/openmm/app/modeller.py", line 485, in addSolvent
2020-02-20T14:51:24.9286189Z     system = forcefield.createSystem(self.topology)
2020-02-20T14:51:24.9287528Z   File "/usr/share/miniconda/envs/test/lib/python3.7/site-packages/simtk/openmm/app/forcefield.py", line 1176, in createSystem
2020-02-20T14:51:24.9288313Z     if generator(self, res):
2020-02-20T14:51:24.9289387Z   File "/usr/share/miniconda/envs/test/lib/python3.7/site-packages/openmoltools/forcefield_generators.py", line 522, in gaffTemplateGenerator
2020-02-20T14:51:24.9290223Z     [template, ffxml] = generateResidueTemplate(molecule)
2020-02-20T14:51:24.9291314Z   File "/usr/share/miniconda/envs/test/lib/python3.7/site-packages/openmoltools/forcefield_generators.py", line 299, in generateResidueTemplate
2020-02-20T14:51:24.9292509Z     run_antechamber(template_name, input_mol2_filename, charge_method=None, net_charge=net_charge, gaff_mol2_filename=gaff_mol2_filename, frcmod_filename=frcmod_filename, gaff_version=gaff_version)
2020-02-20T14:51:24.9293763Z   File "/usr/share/miniconda/envs/test/lib/python3.7/site-packages/openmoltools/amber.py", line 372, in run_antechamber
2020-02-20T14:51:24.9294544Z     raise Exception(msg)
2020-02-20T14:51:24.9295293Z Exception: antechamber failed to produce output mol2 file
2020-02-20T14:51:24.9296431Z command: antechamber -i in.mol2 -fi mol2 -o out.mol2 -fo mol2 -s 2 -at gaff -nc 0

**Comment by hannahbrucemacdonald** [comment]
@jchodera

**Comment by jchodera** [comment]
Here are two different `mol2` representations of pazopanib that both fail in antechamber:
```
antechamber -i pazopanib.mol2 -fi mol2 -o pazopanib.gaff.mol2 -fo mol2 -s 2 -at gaff
antechamber -i pazopanib2.mol2 -fi mol2 -o pazopanib.gaff.mol2 -fo mol2 -s 2 -at gaff 
```
the failure:
```

Welcome to antechamber 19.0: molecular input file processor.

acdoctor mode is on: check and diagnose problems in the input file.
-- Check Format for mol2 File --
   Status: pass
Info: Finished reading file (pazopanib2.mol2); atoms read (54), bonds read (57).
-- Check Unusual Elements --
   Status: pass
-- Check Open Valences --
   Status: pass
-- Check Geometry --
      for those bonded   
      for those not bonded   
   Status: pass
-- Check Weird Bonds --
antechamber: Fatal Error!
Weird atomic valence (5) for atom (ID: 11, Name: C1).
       Possible open valence.
```
However, the SDF from which `pazopanib2.mol2` was generated (using openeye's `convert.py pazopanib.sdf pazopanib2.mol2`) works just fine:
```
$ antechamber -i pazopanib.sdf -fi mdl -o pazopanib.gaff.mol2 -fo mol2 -s 2 -at gaff 

Welcome to antechamber 19.0: molecular input file processor.

acdoctor mode is on: check and diagnose problems in the input file.
-- Check Format for mdl File --
   Status: pass
-- Check Unusual Elements --
   Status: pass
-- Check Open Valences --
   Status: pass
-- Check Geometry --
      for those bonded   
      for those not bonded   
   Status: pass
-- Check Weird Bonds --
   Status: pass
-- Check Number of Units --
   Status: pass
acdoctor mode has completed checking the input file.

Running: /Users/choderaj/miniconda/envs/perses/bin/bondtype -j full -i ANTECHAMBER_BOND_TYPE.AC0 -o ANTECHAMBER_BOND_TYPE.AC -f ac

Running: /Users/choderaj/miniconda/envs/perses/bin/atomtype -i ANTECHAMBER_AC.AC0 -o ANTECHAMBER_AC.AC -p gaff
```
That would suggest that switching these files from mol2 to SDF would solve the problem.

However: the new `openforcefields` `SystemGenerator` _already_ uses SDF to generate inputs to `antechamber`. So I don't think this could still be the reason you are seeing these failures, @hannahbrucemacdonald.

Please post in #646 if you find a new cause!

[pazopanib.zip](https://github.com/choderalab/perses/files/4378091/pazopanib.zip)
