### ISSUE TITLE
Undefined stereochemistry for CDK2 ligand 11

### ISSUE THREAD

**Issue by hannahbrucemacdonald** [choderalab/perses#673]

**Comment by hannahbrucemacdonald** [comment]
<img width="564" alt="Screen Shot 2020-05-19 at 2 56 53 PM" src="https://user-images.githubusercontent.com/43652597/82335998-f11b2200-99e1-11ea-8731-7b492d708bbc.png">

The thione here is recognised by openeye as being chiral.

In `perses.utils.openeye.createOEMolFromSDF` we do two checks:
`oechem.OE3DToInternalStereo(molecule)`  --- which uses the coordinates to work out the stereochemistry of the atoms based on their coordinates _and_
`has_undefined_stereocenters`

Firstly, it says:
`Warning: OE3DToAtomStereo is unable to perceive atom stereo from a flat geometry on atom 44 of molecule '31'`, but if you call `oechem.OE3DToInternalStereo(molecule)` again then it returns True so I'm not sure what's going on.

Secondly, `has_undefined_stereocenters` because S is chiral, but the stereochemistry is undefined. The major thing is that I'm not completely sure what sort of stereochemistry this _should_ be, I'm guessing there is conjugation with the aromatic ring, so the S-C bond has double bond characteristics, so it's sort of an E/Z isomerism? Who knows though.

I could force this to run by just making checking stereochemistry an option or a warning, but I'm not sure that's the right thing to do

**Comment by jchodera** [comment]
@hannahbrucemacdonald : A few things here:
* We should deprecate `perses.utils.openeye.createOEMolFromSDF` in favor of always going through the `openforcefield` toolkit. The equivalent call is
```python
from openforcefield.topology import Molecule
molecule = Molecule.from_file('filename.sdf')
molecule.to_openeye()
```
* Whenever you submit an issue, please provide sufficient information to reproduce the issue---ideally with a minimal test case. If you don't, we either have to spend a lot of time digging to try to figure out what issue you're actually running into, or there is simply no way for us to help. 

I am going to presume you are working with the files in `perses/data/cdk2-example/`. Attempting to read the `CDK2_ligands.sdf` file does indeed result in a stereochemistry error for the ligand with the title `31`:
```
>>> from openforcefield.topology import Molecule
>>> molecules = Molecule.from_file('CDK2_ligands.sdf')
Warning: OE3DToAtomStereo is unable to perceive atom stereo from a flat geometry on atom 44 of molecule '31'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/choderaj/miniconda/envs/perses/lib/python3.7/site-packages/openforcefield/topology/molecule.py", line 2991, in from_file
    allow_undefined_stereo=allow_undefined_stereo)
  File "/Users/choderaj/miniconda/envs/perses/lib/python3.7/site-packages/openforcefield/utils/toolkits.py", line 412, in from_file
    return self._read_oemolistream_molecules(ifs, allow_undefined_stereo, file_path=file_path)
  File "/Users/choderaj/miniconda/envs/perses/lib/python3.7/site-packages/openforcefield/utils/toolkits.py", line 540, in _read_oemolistream_molecules
    allow_undefined_stereo=allow_undefined_stereo)
  File "/Users/choderaj/miniconda/envs/perses/lib/python3.7/site-packages/openforcefield/utils/toolkits.py", line 759, in from_openeye
    raise UndefinedStereochemistryError(msg)
openforcefield.utils.toolkits.UndefinedStereochemistryError: Unable to make OFFMol from OEMol: OEMol has unspecified stereochemistry. oemol.GetTitle(): 31
Problematic atoms are:
Atom atomic num: 16, name: , idx: 44, aromatic: False, chiral: True with bonds:
bond order: 1, chiral: False to atom atomic num: 6, name: , idx: 10, aromatic: True, chiral: False
bond order: 2, chiral: False to atom atomic num: 8, name: , idx: 45, aromatic: False, chiral: False
bond order: 1, chiral: False to atom atomic num: 6, name: , idx: 46, aromatic: False, chiral: False
```
I've extracted that ligand and attached it here: 
[31.sdf.zip](https://github.com/choderalab/perses/files/4653699/31.sdf.zip)
You can replicate this with
```python
from openforcefield.topology import Molecule
molecules = Molecule.from_file('31.sdf')
```
This is related to https://github.com/openforcefield/openforcefield/issues/146, which @j-wags has been keeping up to date. Looks like we need to add thiones as well.

Note that this molecule can be read by adding the `allow_undefined_stereo=True` flag to `Molecule.from_file()`:
```python
>>> molecules = Molecule.from_file('31.sdf', allow_undefined_stereo=True)
Warning: OE3DToAtomStereo is unable to perceive atom stereo from a flat geometry on atom 44 of molecule '31'
Warning (not error because allow_undefined_stereo=True): OEMol has unspecified stereochemistry. oemol.GetTitle(): 31
Problematic atoms are:
Atom atomic num: 16, name: , idx: 44, aromatic: False, chiral: True with bonds:
bond order: 1, chiral: False to atom atomic num: 6, name: , idx: 10, aromatic: True, chiral: False
bond order: 2, chiral: False to atom atomic num: 8, name: , idx: 45, aromatic: False, chiral: False
bond order: 1, chiral: False to atom atomic num: 6, name: , idx: 46, aromatic: False, chiral: False
```
@dfhahn @davidlmobley: Have you run into this issue before with the JACS ligands for CDK2? What did you do in this case?

@j-wags: Tagging you to add this thiones to the set of known stereochemistry issues.

**Comment by dfhahn** [comment]
I had the same issue with this ligand. Per default, the flag `allow_undefined_stereo=True` is now set to true in my workflow.

This issue is also related to [openforcefield/openforcefield#467](https://github.com/openforcefield/openforcefield/issues/467)
