### ISSUE TITLE
Critical error in setting up COVID Moonshot sprint 3

### ISSUE THREAD

**Issue by jchodera** [choderalab/perses#723]
**EDIT:** This first post has a workaround, see next post in thread.

My attempt to use `master` to set up the COVID Moonshot runs into this error:
```
DEBUG:numba.core.ssa:defs defaultdict(<class 'list'>,
            {'$6binary_true_divide.2': [<numba.core.ir.Assign object at 0x2addf8e39850>],
             '$8return_value.3': [<numba.core.ir.Assign object at 0x2addf8e39250>],
             '_56call_function_22_1': [<numba.core.ir.Assign object at 0x2addf8e39ed0>],
             'c_1': [<numba.core.ir.Assign object at 0x2addf8e39550>]})
DEBUG:numba.core.ssa:SSA violators set()
DEBUG:asyncio:Using selector: EpollSelector
2020-08-25 19:46:38,372:(0.00s):root:Detected yaml file: fah_RUN0.yaml
2020-08-25 19:46:38,391:(0.02s):root:spectators: None
2020-08-25 19:46:38,391:(0.00s):root:	Pulling receptor (as pdb or mol2)...
2020-08-25 19:46:38,391:(0.00s):root:	detected ligand file: 2020-08-20-benzotriazoles-dockscores-x10876.sdf
2020-08-25 19:46:38,391:(0.00s):root:	old ligand index: 1; new ligand index: 0
2020-08-25 19:46:38,391:(0.00s):root:	setting up forcefield files...
2020-08-25 19:46:38,391:(0.00s):root:	timestep: 4.0 fs**2.
2020-08-25 19:46:38,391:(0.00s):root:	neq_splitting: V R H O R V
2020-08-25 19:46:38,391:(0.00s):root:	eq_splitting: V R O R V
2020-08-25 19:46:38,391:(0.00s):root:	measuring shadow work: False.
Traceback (most recent call last):
  File "/home/chodera/miniconda/envs/perses/bin/perses-fah", line 33, in <module>
    sys.exit(load_entry_point('perses==0.8.1.dev0', 'console_scripts', 'perses-fah')())
  File "/home/chodera/miniconda/envs/perses/lib/python3.7/site-packages/perses-0.8.1.dev0-py3.7.egg/perses/app/fah_generator.py", line 405, in run
    run_neq_fah_setup(**setup_options)
  File "/home/chodera/miniconda/envs/perses/lib/python3.7/site-packages/perses-0.8.1.dev0-py3.7.egg/perses/app/fah_generator.py", line 272, in run_neq_fah_setup
    setup_dict = run_setup(setup_options, serialize_systems=False, build_samplers=False)
  File "/home/chodera/miniconda/envs/perses/lib/python3.7/site-packages/perses-0.8.1.dev0-py3.7.egg/perses/app/setup_relative_calculation.py", line 388, in run_setup
    ionic_strength = setup_options['ionic_strength'] * unit.molar
KeyError: 'ionic_strength'
```
Input files are on `lilac` here:
```
/data/chodera/chodera/covid-moonshot/synthetic-enumeration
```
See the submission script `submit-ligpairs.sh`, and the YAML file `sprint3.yaml`.

@hannahbrucemacdonald @zhang-ivy @dominicrufa : Can you make debugging this your top priority?

After that, @dominicrufa @zhang-ivy @mcwitt let's schedule a chat about getting unit testing running for this ASAP. We can't have anyone break `master` during  a critical time.

**Comment by jchodera** [comment]
Update: adding `ionic_strength: 0.15` to the `sprint3.yaml` got me a bit further. (Let's still look into why the default was not used!)

Now I have a more puzzling error:
```
2020-08-25 20:00:54,950:(0.00s):root:Box dimensions: (9.8, 9.8, 9.8) and (3.5, 3.5, 3.5)
2020-08-25 20:00:54,950:(0.00s):relative_setup:			_hmass: 4 Da.

2020-08-25 20:00:54,950:(0.00s):relative_setup:Hydrogens will not be constrained for non-water molecules. This may be problematic if using a larger timestep
2020-08-25 20:00:54,950:(0.00s):relative_setup:Setting non bonded method to PME
2020-08-25 20:00:54,950:(0.00s):relative_setup:Handling files for ligands and indices...
2020-08-25 20:00:54,950:(0.00s):relative_setup:Detected .sdf format.  Proceeding...
Traceback (most recent call last):
  File "/home/chodera/miniconda/envs/perses/bin/perses-fah", line 33, in <module>
    sys.exit(load_entry_point('perses==0.8.1.dev0', 'console_scripts', 'perses-fah')())
  File "/home/chodera/miniconda/envs/perses/lib/python3.7/site-packages/perses-0.8.1.dev0-py3.7.egg/perses/app/fah_generator.py", line 405, in run
    run_neq_fah_setup(**setup_options)
  File "/home/chodera/miniconda/envs/perses/lib/python3.7/site-packages/perses-0.8.1.dev0-py3.7.egg/perses/app/fah_generator.py", line 272, in run_neq_fah_setup
    setup_dict = run_setup(setup_options, serialize_systems=False, build_samplers=False)
  File "/home/chodera/miniconda/envs/perses/lib/python3.7/site-packages/perses-0.8.1.dev0-py3.7.egg/perses/app/setup_relative_calculation.py", line 425, in run_setup
    complex_box_dimensions=setup_options['complex_box_dimensions'],solvent_box_dimensions=setup_options['solvent_box_dimensions'], ionic_strength=ionic_strength, remove_constraints=setup_options['remove_constraints'])
  File "/home/chodera/miniconda/envs/perses/lib/python3.7/site-packages/perses-0.8.1.dev0-py3.7.egg/perses/app/relative_setup.py", line 240, in __init__
    self._ligand_oemol_old = createOEMolFromSDF(self._ligand_input, index=self._old_ligand_index, allow_undefined_stereo=True)
TypeError: createOEMolFromSDF() got an unexpected keyword argument 'allow_undefined_stereo'
```

**Comment by jchodera** [comment]
@hannahbrucemacdonald : [You added `allow_undefined_stereo` to the call to `createOEMolFromSDF` 15 hours ago](https://github.com/choderalab/perses/commit/8057935e8d7e2086e4cd62c61306d38ec4479474)---where is the rest of the code needed to run this?
