### ISSUE TITLE
Fix imatinib NCMC null transformation test failures

### ISSUE THREAD

**Issue by jchodera** [choderalab/perses#80]
The imatinib NCMC null transformation test still occasionally fails:
```
======================================================================
ERROR: Testing alchemical null elimination for 'imatinib' with 50 NCMC steps
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/miniconda/envs/_test/lib/python2.7/site-packages/perses-0.1-py2.7.egg/perses/tests/test_elimination.py", line 267, in check_alchemical_null_elimination
    raise Exception(msg)
Exception: Delta F (50 steps switching) = 3.173915 +- 0.367807 kT; should be within 6.000000 sigma of 0
delete logP:
[ 52.83907179  56.96881809  58.72221244  53.66332188  54.39244732
  55.20878563  56.42911385  62.5737624   47.22239953  52.64230924
  52.68643293  51.52396585  48.99477714  52.35681286  50.4809076
  53.9227835   56.61910085  52.69879979  52.22066052  52.8527985
  53.48836845  51.30178305  56.78153917  56.04516468  51.6749105
  55.60416723  51.679132    49.14696474  51.27811396  52.11830492]
insert logP:
[-56.94178584 -57.93855619 -75.74928178 -57.65467855 -64.17625056
 -63.93724275 -61.50533476 -69.62354963 -57.2744736  -79.88086955
 -56.74460312 -60.32094396 -55.35969296 -56.36628618 -53.71085795
 -66.62961333 -60.6884257  -65.73408047 -53.86550795 -59.83222306
 -64.63476613 -56.69728159 -60.02577208 -73.42986568 -59.48264145
 -58.47741466 -62.61625228 -51.43052224 -52.73681281 -54.31872933]
logP:
[ -4.10271405  -0.9697381  -17.02706934  -3.99135666  -9.78380324
  -8.72845712  -5.07622091  -7.04978723 -10.05207407 -27.23856031
  -4.05817019  -8.79697811  -6.36491582  -4.00947332  -3.22995035
 -12.70682983  -4.06932486 -13.03528068  -1.64484743  -6.97942456
 -11.14639768  -5.39549854  -3.24423292 -17.384701    -7.80773094
  -2.87324743 -10.93712028  -2.2835575   -1.45869886  -2.20042441]
-------------------- >> begin captured logging << --------------------
```
I thought this was due to the lack of initial equilibration, but it could also be due to the fact that the samples are not really uncorrelated and so the statistical error is being underestimated.  Or there could be something actually wrong here.  I will investigate.

**Comment by jchodera** [comment]
This was resolved by https://github.com/pandegroup/openmm/pull/1384
