### ISSUE TITLE
`SamplerExample` not running

### ISSUE THREAD

**Issue by ijpulidos** [choderalab/perses#842]
After fixing obvious filename issues, when I try to run the `SamplerExample` example I get the following error message:
```
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/perses-dev-test/bin/perses-relative", line 33, in <module>
    sys.exit(load_entry_point('perses', 'console_scripts', 'perses-relative')())
  File "/home/user/workdir/ChoderaLab/repos/perses/perses/app/setup_relative_calculation.py", line 743, in run
    setup_dict = run_setup(setup_options)
  File "/home/user/workdir/ChoderaLab/repos/perses/perses/app/setup_relative_calculation.py", line 450, in run_setup
    fe_setup = RelativeFEPSetup(ligand_file, old_ligand_index, new_ligand_index, forcefield_files,phases=phases,
  File "/home/user/workdir/ChoderaLab/repos/perses/perses/app/relative_setup.py", line 373, in __init__
    self._complex_topology_old_solvated, self._complex_positions_old_solvated, self._complex_system_old_solvated = self._solvate_system(
  File "/home/user/workdir/ChoderaLab/repos/perses/perses/app/relative_setup.py", line 824, in _solvate_system
    modeller.addSolvent(self._system_generator.forcefield, model=model, padding=self._padding, ionicStrength=ionic_strength)
  File "/home/user/miniconda3/envs/perses-dev-test/lib/python3.9/site-packages/simtk/openmm/app/modeller.py", line 485, in addSolvent
    system = forcefield.createSystem(self.topology)
  File "/home/user/miniconda3/envs/perses-dev-test/lib/python3.9/site-packages/simtk/openmm/app/forcefield.py", line 1179, in createSystem
    templateForResidue = self._matchAllResiduesToTemplates(data, topology, residueTemplates, ignoreExternalBonds)
  File "/home/user/miniconda3/envs/perses-dev-test/lib/python3.9/site-packages/simtk/openmm/app/forcefield.py", line 1393, in _matchAllResiduesToTemplates
    raise ValueError('No template found for residue %d (%s).  %s' % (res.index+1, res.name, _findMatchErrors(self, res)))
ValueError: No template found for residue 556 (MOL).  This might mean your input topology is missing some atoms or bonds, or possibly that you are using the wrong force field.
```
So I guess the ligand gets some generic/unknown residue name `MOL` that `openmm` does not know how to handle (no parameters for it). Any ideas why this may be happening?

**Comment by ijpulidos** [comment]
Examples are being cleaned. This is not relevant now.
