### ISSUE TITLE
`mcl1-example` incorrect pdb file

### ISSUE THREAD

**Issue by ijpulidos** [choderalab/perses#843]
While trying to run the `mcl1-example` in the examples directory I run into the following issue:
```
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/perses-dev-test/bin/perses-relative", line 33, in <module>
    sys.exit(load_entry_point('perses', 'console_scripts', 'perses-relative')())
  File "/home/user/workdir/ChoderaLab/repos/perses/perses/app/setup_relative_calculation.py", line 743, in run
    setup_dict = run_setup(setup_options)
  File "/home/user/workdir/ChoderaLab/repos/perses/perses/app/setup_relative_calculation.py", line 450, in run_setup
    fe_setup = RelativeFEPSetup(ligand_file, old_ligand_index, new_ligand_index, forcefield_files,phases=phases,
  File "/home/user/workdir/ChoderaLab/repos/perses/perses/app/relative_setup.py", line 373, in __init__
    self._complex_topology_old_solvated, self._complex_positions_old_solvated, self._complex_system_old_solvated = self._solvate_system(
  File "/home/user/workdir/ChoderaLab/repos/perses/perses/app/relative_setup.py", line 824, in _solvate_system
    modeller.addSolvent(self._system_generator.forcefield, model=model, padding=self._padding, ionicStrength=ionic_strength)
  File "/home/user/miniconda3/envs/perses-dev-test/lib/python3.9/site-packages/simtk/openmm/app/modeller.py", line 485, in addSolvent
    system = forcefield.createSystem(self.topology)
  File "/home/user/miniconda3/envs/perses-dev-test/lib/python3.9/site-packages/simtk/openmm/app/forcefield.py", line 1179, in createSystem
    templateForResidue = self._matchAllResiduesToTemplates(data, topology, residueTemplates, ignoreExternalBonds)
  File "/home/user/miniconda3/envs/perses-dev-test/lib/python3.9/site-packages/simtk/openmm/app/forcefield.py", line 1393, in _matchAllResiduesToTemplates
    raise ValueError('No template found for residue %d (%s).  %s' % (res.index+1, res.name, _findMatchErrors(self, res)))
ValueError: No template found for residue 150 (HIS).  The set of atoms matches CHIP, but the bonds are different.  Perhaps the chain is missing a terminal group?
```
I guess there is something wrong with the `MCL1_protein_fixed.pdb` file. If I check the mentioned HIS residue (resid 150) with pymol, I do find some unexpected conformation, as shown in the picture
![image](https://user-images.githubusercontent.com/2949729/128943612-8b4dbf44-9aa9-4b49-b992-4502fc109b9c.png)

**Comment by ijpulidos** [comment]
The histidine with issues is in one of the terminals of the protein. I tried capping this terminal using PyMol's mutagenesis and I get what it seems to be a "better" conformation, but I still get the following issue when running the example
```
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/perses-dev-test/bin/perses-relative", line 33, in <module>
    sys.exit(load_entry_point('perses', 'console_scripts', 'perses-relative')())
  File "/home/user/workdir/ChoderaLab/repos/perses/perses/app/setup_relative_calculation.py", line 743, in run
    setup_dict = run_setup(setup_options)
  File "/home/user/workdir/ChoderaLab/repos/perses/perses/app/setup_relative_calculation.py", line 450, in run_setup
    fe_setup = RelativeFEPSetup(ligand_file, old_ligand_index, new_ligand_index, forcefield_files,phases=phases,
  File "/home/user/workdir/ChoderaLab/repos/perses/perses/app/relative_setup.py", line 373, in __init__
    self._complex_topology_old_solvated, self._complex_positions_old_solvated, self._complex_system_old_solvated = self._solvate_system(
  File "/home/user/workdir/ChoderaLab/repos/perses/perses/app/relative_setup.py", line 824, in _solvate_system
    modeller.addSolvent(self._system_generator.forcefield, model=model, padding=self._padding, ionicStrength=ionic_strength)
  File "/home/user/miniconda3/envs/perses-dev-test/lib/python3.9/site-packages/simtk/openmm/app/modeller.py", line 485, in addSolvent
    system = forcefield.createSystem(self.topology)
  File "/home/user/miniconda3/envs/perses-dev-test/lib/python3.9/site-packages/simtk/openmm/app/forcefield.py", line 1179, in createSystem
    templateForResidue = self._matchAllResiduesToTemplates(data, topology, residueTemplates, ignoreExternalBonds)
  File "/home/user/miniconda3/envs/perses-dev-test/lib/python3.9/site-packages/simtk/openmm/app/forcefield.py", line 1393, in _matchAllResiduesToTemplates
    raise ValueError('No template found for residue %d (%s).  %s' % (res.index+1, res.name, _findMatchErrors(self, res)))
ValueError: No template found for residue 150 (HIS).  The set of atoms matches HID, but the bonds are different.
```
So I guess we may indeed need a different/correct PDB for this example to work. You can see the PDB used in this case here 
[mcl1_capped_pymol.tar.gz](https://github.com/choderalab/perses/files/6964845/mcl1_capped_pymol.tar.gz)

**Comment by ijpulidos** [comment]
Examples are being cleaned. Not relevant now.
